### ISSUE TITLE
API endpoint cannot be accessed by browser

### ISSUE THREAD

**Issue by sxzz** [jsr-io/jsr#156]
- Add CORS header
<img width="1072" alt="image" src="https://github.com/jsr-io/jsr/assets/6481596/676c7214-6966-45fa-b12d-b5aa5eea963c">

- Cannot visit by browser page, it shows 404 page. It could caused by `accept` header.

https://jsr.io/@std/assert/meta.json

```
// 404 page
❯ curl 'https://jsr.io/@std/assert/meta.json' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7'

// works without accept header
❯ curl 'https://jsr.io/@std/assert/meta.json'
```

**Comment by marvinhagemeister** [comment]
Wondering if we should move the `meta.json` endpoint to the api server instead. That way we can avoid the whole accept header stuff which seems to cause most of the confusion.

**Comment by lucacasonato** [comment]
It's not just the meta.json tho - it's all the module code also.

**Comment by takker99** [comment]
I was wondering about the current status of this issue. I'd really like to see this bug fixed as I need to call the API from the browser too! If possible, I'm also willing to help with the PR.

Thanks!

**Comment by josephrocca** [comment]
@lucacasonato I notice that CORS headers are added for `fetch(...)`, but not for `import(...)` - is this correct behavior? I.e. there is no intention to support importing from the browser?

And if that's true, then I'm wondering whether jsr's position would change on this if Cloudflare provided the bandwidth, as they do with jsdelivr and cdnjs? I.e. is it due to bandwidth sustainability concerns?

This would be an awesome point of improvement/differentiation for JSR I think, especially if a `mod.ts?js` type approach were used for transpilation to vanilla JS.
