### ISSUE TITLE
Bug in the *.d.ts transform for package

### ISSUE THREAD

**Issue by nikitavoloboev** [jsr-io/jsr#364]
JSR Package: https://jsr.io/@nikiv/utils
Code for package: https://github.com/nikitavoloboev/ts-utils
Consumer of package: https://github.com/nikitavoloboev/python

<img width="1234" alt="image" src="https://github.com/jsr-io/jsr/assets/6391776/4a224b47-dd08-4bed-9bd5-1e71cd636582">

As @marvinhagemeister said on Discord:

<img width="1097" alt="image" src="https://github.com/jsr-io/jsr/assets/6391776/1227fb09-6e6b-4967-ab9d-59e3ae199947">

**Comment by nikitavoloboev** [comment]
This issue has been reported by others so its not tied to my specific setup. Something is off about either how JSR publishes the types or tsconfig or something else, unclear.

Thank you for the help. ♥️

**Comment by nikitavoloboev** [comment]
<img width="836" alt="image" src="https://github.com/jsr-io/jsr/assets/6391776/d634ba79-e96c-4215-ab5e-ecc58e6c61df">

tried above and all kinds of `tsconfig` configurations, all failed.

**Comment by nikitavoloboev** [comment]
It's like the types are not present in the JSR?

**Comment by marvinhagemeister** [comment]
Took a look into this and it's a bug in our npm transform. When we generate the declaration file we're still pointing imports to the original `*.ts` files. But because those are transpiled to `*.js` too and not shipped within the npm package, these files are not found anymore.

## Steps to reproduce

1. Publish this package:
```ts
// bar.ts
export function add(a: number, b: number): number {
  return a + b;
}
```
```ts
// foo.ts
export { add } from "./bar.ts";
```
```jsonc
// deno.jsonc
{
  "name": "@marvinh-test/re-export",
  "version": "0.0.1",
  "exports": {
    ".": "./foo.ts"
  }
}
```
2. Install generated npm tarball: `npx jsr add @marvinh-test/re-export`
