### ISSUE TITLE
remove TLS 1.0 & 1.1 support

### ISSUE THREAD

**Issue by crowlKats** [jsr-io/jsr#430]

**Comment by adamgreg** [comment]
Ah, you beat me to it @crowlKats 😊

Here's the message I sent on Discord for context:

Hi, I'm very keen to transition my dependencies to JSR, but my client's IT operates an allow list for external domains, and their policy won't allow jsr.io because of its support for TLS 1.0 and 1.1.

Report here: https://www.ssllabs.com/ssltest/analyze.html?d=jsr.io&s=34.120.78.157&hideResults=on

Is there any chance of JSR dropping support for these deprecated versions of TLS? NPM does not seem to support them.

**Comment by adamgreg** [comment]
Amazing, thanks!
