### ISSUE TITLE
TypeScript source files in "types" exports can cause compilation errors (npm)

### ISSUE THREAD

**Issue by frangio** [jsr-io/jsr#446]
In https://github.com/jsr-io/jsr/pull/377 the package.json files for npm where changed so that the source .ts files are used for "types" exports instead of .d.ts files as was done previously. This is not right, because when such a package is installed and imported in a TypeScript file, TypeScript will try to compile the dependency source file with the project's compilation settings, which may be different and cause compilation errors, for example, due to different settings for `noUncheckedIndexedAccess`.

The original issue https://github.com/jsr-io/jsr/issues/313 that was marked as fixed proposed adding declaration maps and source files _in addition to_ the compiled .d.ts files that go in "types" exports. This allows "go to definition" to work as expected, and does not cause the compilation errors that the current approach causes.

**Comment by lucacasonato** [comment]
Oh this is not intentional - do you have an example where this is happening? It should not point to `.ts` files ever 😓

**Comment by frangio** [comment]
I noticed it when installing the package [@noble/secp256k1](https://jsr.io/@noble/secp256k1).

**Comment by alexgleason** [comment]
Wow, this explains a lot! I have been fighting with this issue for several days. Source files of JSR packages are getting type-checked.

![image](https://github.com/jsr-io/jsr/assets/3639540/0f8b9187-4476-4ce6-b789-ec6e88983c34)

`AbortSignal.any` is not available in vanilla TypeScript (even though browsers support it). And my client code in Node is getting type errors from the package implementation instead of just caring about the signatures.

**Comment by lucacasonato** [comment]
Great - thanks. I'll get this fixed today

**Comment by lucacasonato** [comment]
I can reproduce - this happens for packages that are using slow types, so where no `d.ts` file is emitted.

**Comment by lucacasonato** [comment]
@alexgleason This is now fixed. Remove your lockfile and re-run `npm i` to get an updated `node_modules/` folder.

**Comment by alexgleason** [comment]
It works now. Thank you @lucacasonato !! :rocket:
