### ISSUE TITLE
Underscores in scope name

### ISSUE THREAD

**Issue by olyop** [jsr-io/jsr#579]
I notcied scope names cannot have underscores contained in them and I have an npm scope that has an underscore. I'm sure there's a good reason for it and I would agree scope names should use hypens instead of underscores as it's the standard case convention the JS world seems to use but thought I would create an issue for backwards compatibility purposes.

FYI I wasn't able to find any package names in the top 10,000 that contain an underscore in their name using `@[^/]*_[^/]*\/`

**Comment by lucacasonato** [comment]
We are intentionally only allowing hyphens. It prevents attacks where users register a malicious scope with an underscore instead of a hyphen to then fool users into installing their malicious package (which looks like it has the right name).

We also disallow it because it is confusing for users to have to remember "did this package / scope" use underscores or hyphens. This is an annoying problem in the Rust community for example.
