### ISSUE TITLE
Package's github link 

### ISSUE THREAD

**Issue by lorens-osman-dev** [jsr-io/jsr#618]
Why is there no GitHub link for the packages?  It will be a nice feature if you provide a link that points to the page of package's GitHub page.

**Comment by marvinhagemeister** [comment]
Maybe we should move this to a different place. Could be an effect of ["banner blindness"](https://en.wikipedia.org/wiki/Banner_blindness#:~:text=Banner%20blindness%20is%20a%20phenomenon,ignore%20is%20called%20banner%20noise.) where it's to close to something not immediately relevant to the user and being missed because of that.

<img width="817" alt="Screenshot 2024-06-24 at 09 36 06" src="https://github.com/jsr-io/jsr/assets/1062408/16274119-4fce-4773-abca-4322d0e0b199">

**Comment by lorens-osman-dev** [comment]
oh my god i am blind , sorry for wasting your time

**Comment by lorens-osman-dev** [comment]
what about this package ? that very confusing 

![IMG_20240624_120746](https://github.com/jsr-io/jsr/assets/114411575/7a2ea318-d6ac-4ebc-8eda-4415839341de)

**Comment by marvinhagemeister** [comment]
Looks like they haven't added a link to the GitHub repository in the package metadata. The simply didn't fill out this field.

**Comment by marvinhagemeister** [comment]
@lorens-osman-dev Filed an upstream issue on their tracker about the missing GitHub link: https://github.com/bsorrentino/pdf-tools/issues/9

**Comment by lorens-osman-dev** [comment]
From a user experience (UX) standpoint, whenever there are files listed in
the "Files" tab, including a mandatory GitHub link would be beneficial.
While filing issues for each package might seem like a solution, it doesn't
guarantee that a GitHub link will be provided. This creates an additional
burden for JSR users and can lead to negative feedback loop amoung JSR
users.   A simpler and more efficient approach would be to enforce
including a GitHub link during package submission.

best

**Comment by alectrocute** [comment]
Addressing this in https://github.com/jsr-io/jsr/pull/625. I feel this chip needs to be more obviously an external link. We should address, in the long-term, making GitHub links mandatory.
