### ISSUE TITLE
url to latest version of a file in jsr

### ISSUE THREAD

**Issue by alan-khosro** [jsr-io/jsr#771]
Deno lest us use `deno run https://the-url` which is great.
JSR lets us reference to a specific file.
For small scripts (for CLI tasks) I can do (for instance):
```sh
deno run -A https://jsr.io/@invisement/imports-graph/0.1.5/imports-graph.ts ./ui/src .
```
Which is really great.
But I could not figure out how to reference to the latest version of that particular file. Something like:
https://jsr.io/@invisement/imports-graph/@latest/imports-graph.ts
Or similar. 
If there is such possibility, how can I do it (and please add to your documentation). If not: feature request.

**Comment by marvinhagemeister** [comment]
The equivalent command is:

```sh
deno run -A jsr:@invisement/imports-graph@^0
```

Currently, there are no tags on JSR, but you can work around that by adding the `@^MAJOR` version constraint to the command. That will always pull in the most recent version of said package. At the time of this writing the `@invisement/imports-graph` package hasn't done a `1.0.0` release so that is `@^0`. Once they cut a `1.0.0` it will be `@^1`.

**Comment by alan-khosro** [comment]
Works like a charm. Thanks!
I could not find it in your documentations.
