### ISSUE TITLE
Symbol search bug: `almost` finds `assertAlmostEqual` but `almostE` finds nothing

### ISSUE THREAD

**Issue by cspotcode** [jsr-io/jsr#775]
Symbol search appears to be buggy, or else the behavior is not intuitive.

Looking at this page for example: https://jsr.io/@std/assert/doc

When I search for `almost` and then `almostE` I would expect to get the same results, but the latter shows nothing.

![image](https://github.com/user-attachments/assets/201a5b4a-c5ac-4857-a333-e635813dcef9)
![image](https://github.com/user-attachments/assets/8ee815ee-0b8e-40ab-930f-de3fb9e380c1)

**Comment by mbhrznr** [comment]
this seems to be caused by `tokenize`.  
the tokens produced for `assertAlmostEquals` are the following:
```ts
["assert", "almost", "equals", "assertalmostequals"]
```

as `search` currently doesn't have any `tolerance`, `orama` tries to match these tokens pretty closely, even though `exact` isn't set.
any combination of these tokens as search input would lead to the expected result.

going forward we could think about:
- adding some `tolerance`, which would mean that the local symbol search would behave differently 
- adding more `tokens` by (potentially) joining the split elements w/ the next element in the token array

for the latter, the example output could look like this then:
```ts
["assert", "almost", "equals", "assertalmost", "almostequals" ,"assertalmostequals"]
```

**Comment by lucacasonato** [comment]
I think both of those seem acceptable. @mbhrznr do you want to submit a PR?
